// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DropEvent tells the UI which files the OS dropped onto which folder.
 */
export interface DropEvent {
    "dir": string;
    "files": string[] | null;
}
