// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CrossDrag is sent to the window under a drag that left its own window.
 * X and Y are relative to the page.
 */
export interface CrossDrag {
    /**
     * "over", "leave" or "drop"
     */
    "type": string;
    "x": number;
    "y": number;
    "copy": boolean;
    "payload": DragPayload | null;
}

/**
 * DragPayload is what a window drags: the paths of the items and a label for
 * the drag icon.
 */
export interface DragPayload {
    "kind": string;
    "paths": string[] | null;
    "allDirs": boolean;
    "label": string;
}

/**
 * DropEvent tells the UI which files the OS dropped onto which folder.
 */
export interface DropEvent {
    "dir": string;
    "files": string[] | null;
}
