// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService opens additional browser windows, like Nautilus' Ctrl+N.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * NewWindow opens a window showing path (the home folder when empty).
 */
export function NewWindow(path: string): $CancellablePromise<void> {
    return $Call.ByID(3096593237, path);
}
