// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService opens additional browser windows, like Nautilus' Ctrl+N.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Clipboard returns the items waiting to be pasted, or nil.
 */
export function Clipboard(): $CancellablePromise<$models.ItemClipboard | null> {
    return $Call.ByID(919387997);
}

/**
 * ClipboardFiles returns the local paths of the files on the system
 * clipboard.
 */
export function ClipboardFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1373921720);
}

/**
 * ClipboardHasFiles reports whether the system clipboard holds files copied
 * in another application.
 */
export function ClipboardHasFiles(): $CancellablePromise<boolean> {
    return $Call.ByID(2505668690);
}

/**
 * NewWindow opens a window showing path (the home folder when empty).
 */
export function NewWindow(path: string): $CancellablePromise<void> {
    return $Call.ByID(3096593237, path);
}

/**
 * SetClipboard puts items on the clipboard shared by all windows; nil (or no
 * paths) clears it.
 */
export function SetClipboard(c: $models.ItemClipboard | null): $CancellablePromise<void> {
    return $Call.ByID(1010165295, c);
}

/**
 * StartDrag hands the calling window's item drag over to the platform once
 * the pointer leaves the window. It returns false when that isn't possible;
 * the window then keeps the drag to itself.
 */
export function StartDrag(p: $models.DragPayload): $CancellablePromise<boolean> {
    return $Call.ByID(522538417, p);
}
