// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Subscription {
    "id": string;
    "name": string;
    "type": string;
    "file_size_limit": number;
    "storage_limit": number;
    "monthly_transfer_cap": number;
}

export interface User {
    "id": string;
    "username": string;
    "email": string;
    "subscription": Subscription;
    "storage_space_used": number;
    "filesystem_storage_used": number;
    "filesystem_node_count": number;
    "monthly_transfer_cap": number;
    "monthly_transfer_used": number;
    "balance_micro_eur": number;
}
