// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService manages credentials and preferences.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nova$0 from "../internal/nova/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DefaultServer(): $CancellablePromise<string> {
    return $Call.ByID(3027766693);
}

export function Prefs(): $CancellablePromise<config$0.Prefs> {
    return $Call.ByID(1516396029);
}

/**
 * Refresh reloads the user info (quota etc).
 */
export function Refresh(): $CancellablePromise<nova$0.User | null> {
    return $Call.ByID(4263875728);
}

/**
 * Restore validates the saved key, if any, and returns the session.
 */
export function Restore(): $CancellablePromise<$models.Session> {
    return $Call.ByID(684558421);
}

export function SavePrefs(p: config$0.Prefs): $CancellablePromise<void> {
    return $Call.ByID(52042566, p);
}

/**
 * SignIn exchanges a username and password for an API key.
 */
export function SignIn(server: string, username: string, password: string): $CancellablePromise<$models.Session> {
    return $Call.ByID(3803674863, server, username, password);
}

/**
 * SignInWithKey signs in using an existing API key.
 */
export function SignInWithKey(server: string, key: string): $CancellablePromise<$models.Session> {
    return $Call.ByID(1672214862, server, key);
}

/**
 * SignOut forgets the stored key. Keys created by SignIn are revoked;
 * keys the user pasted in are left alone since they may be used elsewhere.
 */
export function SignOut(): $CancellablePromise<void> {
    return $Call.ByID(157681364);
}
