// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Bookmark {
    "name": string;
    "path": string;
}

/**
 * Prefs are UI preferences owned by the frontend.
 */
export interface Prefs {
    /**
     * "grid" | "list"
     */
    "view": string;

    /**
     * show dotfiles
     */
    "showHidden": boolean;

    /**
     * "name" | "size" | "modified" | "type"
     */
    "sortBy": string;
    "sortDesc": boolean;

    /**
     * icon zoom level 0..4
     */
    "zoom": number;
    "sidebarOpen": boolean;

    /**
     * "system" | "light" | "dark"
     */
    "theme": string;
    "bookmarks": Bookmark[] | null;

    /**
     * starred file and folder paths
     */
    "starred": string[] | null;
    "foldersFirst": boolean;
}
