// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccountService backs the settings page: usage statistics, synced bookmarks
 * and the recommended folder layout.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../internal/config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateRecommendedFolders creates the recommended folders that don't exist
 * yet and returns the paths it created. It never deletes or renames anything.
 */
export function CreateRecommendedFolders(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2810994358);
}

/**
 * RecommendedFolders lists the recommended folders and which already exist.
 */
export function RecommendedFolders(): $CancellablePromise<$models.FolderStatus[] | null> {
    return $Call.ByID(1187177002);
}

/**
 * SaveBookmarks stores the sidebar bookmarks locally and on the server.
 * Server entries the sidebar can't show are kept as they are.
 */
export function SaveBookmarks(list: config$0.Bookmark[] | null): $CancellablePromise<void> {
    return $Call.ByID(3252672156, list);
}

/**
 * SyncBookmarks returns the bookmarks stored on the server and saves them
 * locally. When the server has none yet, the local bookmarks are uploaded.
 */
export function SyncBookmarks(): $CancellablePromise<config$0.Bookmark[] | null> {
    return $Call.ByID(130209670);
}

/**
 * Usage returns egress ("egress", bytes) or downloads ("downloads") over the
 * last `minutes`, bucketed per `interval` minutes.
 */
export function Usage(kind: string, minutes: number, interval: number): $CancellablePromise<$models.UsageSeries | null> {
    return $Call.ByID(2925259529, kind, minutes, interval);
}
