// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FilesService exposes filesystem operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateFolder creates dir/name, returning the new path.
 */
export function CreateFolder(dir: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(1024156154, dir, name);
}

/**
 * Delete permanently deletes paths.
 */
export function Delete(paths: string[] | null): $CancellablePromise<$models.OpResult | null> {
    return $Call.ByID(781945201, paths);
}

/**
 * EmptyTrash permanently deletes everything in the trash.
 */
export function EmptyTrash(): $CancellablePromise<void> {
    return $Call.ByID(1399227767);
}

export function List(p: string): $CancellablePromise<$models.Folder | null> {
    return $Call.ByID(167406178, p);
}

export function Measure(p: string): $CancellablePromise<$models.FolderSize | null> {
    return $Call.ByID(3537729130, p);
}

/**
 * Move moves paths into destDir. Name clashes get a unique name.
 */
export function Move(paths: string[] | null, destDir: string): $CancellablePromise<$models.OpResult | null> {
    return $Call.ByID(459144579, paths, destDir);
}

/**
 * Rename renames p within its directory.
 */
export function Rename(p: string, newName: string): $CancellablePromise<string> {
    return $Call.ByID(2005606928, p, newName);
}

/**
 * Restore moves trashed items back to where they came from.
 */
export function Restore(paths: string[] | null): $CancellablePromise<$models.OpResult | null> {
    return $Call.ByID(679835524, paths);
}

/**
 * Search finds entries below dir whose name matches term.
 */
export function Search(dir: string, term: string): $CancellablePromise<$models.Entry[] | null> {
    return $Call.ByID(1331637398, dir, term);
}

/**
 * Share enables or disables the public link and returns the link URL.
 */
export function Share(p: string, shared: boolean): $CancellablePromise<string> {
    return $Call.ByID(4053182397, p, shared);
}

export function Stat(p: string): $CancellablePromise<$models.Entry | null> {
    return $Call.ByID(1945997868, p);
}

/**
 * StatMany returns entries for the given paths, skipping ones that no longer exist.
 */
export function StatMany(paths: string[] | null): $CancellablePromise<$models.Entry[] | null> {
    return $Call.ByID(1735041219, paths);
}

/**
 * Trash moves paths into the trash folder and remembers where they came from.
 */
export function Trash(paths: string[] | null): $CancellablePromise<$models.OpResult | null> {
    return $Call.ByID(2905769052, paths);
}

/**
 * TrashCount returns the number of items in the trash.
 */
export function TrashCount(): $CancellablePromise<number> {
    return $Call.ByID(202191747);
}
