// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FilesService exposes filesystem operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CacheForView downloads a file into the app cache for the phone's viewer and
 * returns its path relative to the cache ("view/…"). Android serves that
 * file straight from disk, with seeking, instead of passing the whole file
 * through the WebView bridge. A file already fetched is reused.
 */
export function CacheForView(p: string): $CancellablePromise<string> {
    return $Call.ByID(495763454, p);
}

/**
 * CreateFolder creates dir/name, returning the new path.
 */
export function CreateFolder(dir: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(1024156154, dir, name);
}

/**
 * Delete permanently deletes paths.
 */
export function Delete(paths: string[] | null): $CancellablePromise<$models.OpResult | null> {
    return $Call.ByID(781945201, paths);
}

/**
 * EmptyTrash permanently deletes everything in the trash.
 */
export function EmptyTrash(): $CancellablePromise<void> {
    return $Call.ByID(1399227767);
}

export function List(p: string): $CancellablePromise<$models.Folder | null> {
    return $Call.ByID(167406178, p);
}

export function Measure(p: string): $CancellablePromise<$models.FolderSize | null> {
    return $Call.ByID(3537729130, p);
}

/**
 * Move moves paths into destDir. Name clashes get a unique name.
 */
export function Move(paths: string[] | null, destDir: string): $CancellablePromise<$models.OpResult | null> {
    return $Call.ByID(459144579, paths, destDir);
}

/**
 * Recent returns the most recently modified files, newest first.
 */
export function Recent(fresh: boolean): $CancellablePromise<$models.Entry[] | null> {
    return $Call.ByID(2862733549, fresh);
}

/**
 * Rename renames p within its directory.
 */
export function Rename(p: string, newName: string): $CancellablePromise<string> {
    return $Call.ByID(2005606928, p, newName);
}

/**
 * Restore moves trashed items back to where they came from. An item without
 * an origin goes to the home folder under its trashed name.
 */
export function Restore(paths: string[] | null): $CancellablePromise<$models.OpResult | null> {
    return $Call.ByID(679835524, paths);
}

/**
 * Search finds entries below dir whose name matches term.
 */
export function Search(dir: string, term: string): $CancellablePromise<$models.Entry[] | null> {
    return $Call.ByID(1331637398, dir, term);
}

/**
 * SetLinkAccess changes what anyone with the link may do with p.
 */
export function SetLinkAccess(p: string, a: $models.Access): $CancellablePromise<$models.Sharing | null> {
    return $Call.ByID(4196174016, p, a);
}

/**
 * SetPeople replaces the list of users p is shared with. Names can be
 * usernames or e-mail addresses; the server rejects unknown ones.
 */
export function SetPeople(p: string, people: $models.Person[] | null): $CancellablePromise<$models.Sharing | null> {
    return $Call.ByID(990717949, p, people);
}

/**
 * ShareLink returns a link to p, first making p public when neither it nor a
 * parent folder is.
 */
export function ShareLink(p: string): $CancellablePromise<string> {
    return $Call.ByID(3300472449, p);
}

/**
 * Shared returns the items that anyone with the link or named people can
 * reach. Items inside a shared folder are left out; the folder stands for them.
 */
export function Shared(fresh: boolean): $CancellablePromise<$models.Entry[] | null> {
    return $Call.ByID(690633371, fresh);
}

/**
 * Sharing returns the sharing settings of p.
 */
export function Sharing(p: string): $CancellablePromise<$models.Sharing | null> {
    return $Call.ByID(2651899766, p);
}

export function Stat(p: string): $CancellablePromise<$models.Entry | null> {
    return $Call.ByID(1945997868, p);
}

/**
 * StatMany returns entries for the given paths, skipping ones that no longer exist.
 */
export function StatMany(paths: string[] | null): $CancellablePromise<$models.Entry[] | null> {
    return $Call.ByID(1735041219, paths);
}

/**
 * StopSharing turns off p's public link. People it is shared with keep access.
 */
export function StopSharing(p: string): $CancellablePromise<void> {
    return $Call.ByID(785526622, p);
}

/**
 * Trash moves paths into the trash and records where they came from.
 */
export function Trash(paths: string[] | null): $CancellablePromise<$models.OpResult | null> {
    return $Call.ByID(2905769052, paths);
}

/**
 * TrashCount returns the number of items in the trash.
 */
export function TrashCount(): $CancellablePromise<number> {
    return $Call.ByID(202191747);
}
