// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nova$0 from "../internal/nova/models.js";

/**
 * Access is what someone may do with a shared file or folder. Write and
 * Delete only mean something for folders.
 */
export interface Access {
    "read": boolean;
    "write": boolean;
    "delete": boolean;
}

/**
 * Entry is a filesystem node as the UI sees it.
 */
export interface Entry {
    "id": string;
    "name": string;
    "path": string;
    "isDir": boolean;
    "size": number;
    "mime": string;
    "modified": string;
    "created": string;
    "mode": string;
    "owner": string;
    "sha256": string;

    /**
     * Shared: someone besides the owner can reach it. Public: through its link.
     */
    "shared": boolean;
    "public": boolean;

    /**
     * Trash only: where the item came from.
     */
    "origPath"?: string;
    "deletedAt"?: string | null;
}

export interface Folder {
    "path": string;
    "crumbs": Entry[] | null;
    "children": Entry[] | null;
    "canWrite": boolean;
}

/**
 * FolderSize sums file sizes below p. Directories only report their own size.
 */
export interface FolderSize {
    "bytes": number;
    "files": number;
    "folders": number;
}

/**
 * FolderStatus says whether a recommended folder exists already.
 */
export interface FolderStatus {
    "name": string;
    "path": string;
    "exists": boolean;
}

/**
 * OpResult reports partial failure of a batch operation.
 */
export interface OpResult {
    "done": string[] | null;
    "errors": string[] | null;

    /**
     * From holds the source path of each Done entry, for operations that move.
     */
    "from"?: string[] | null;
}

/**
 * Person is a nova.storage user the item is shared with.
 */
export interface Person {
    "name": string;
    "access": Access;
}

/**
 * Session is the signed-in state shown to the UI.
 */
export interface Session {
    "signedIn": boolean;
    "server": string;
    "user": nova$0.User | null;
}

/**
 * Sharing describes who can reach an item, as the Share dialog shows it.
 */
export interface Sharing {
    "path": string;
    "isDir": boolean;

    /**
     * CanShare is false when the account's plan doesn't include sharing.
     */
    "canShare": boolean;

    /**
     * Link is what anyone with this item's own link may do.
     */
    "link": Access;

    /**
     * URL opens the item in the browser, through its own link or that of a
     * shared parent folder. Empty when neither is public.
     */
    "url": string;

    /**
     * DirectURL downloads a file straight away (a hotlink).
     */
    "directUrl": string;

    /**
     * PeopleURL is the item's own link, for the people it is shared with. It
     * only works for them once they sign in, unless the item is public.
     */
    "peopleUrl": string;

    /**
     * Via is the path of the parent folder whose link URL goes through, when
     * the item isn't public itself.
     */
    "via": string;
    "people": Person[] | null;

    /**
     * Abuse is set when the item was reported and taken down.
     */
    "abuse": string;
}

/**
 * Transfer is one batch job (upload of several files, download of a folder...).
 */
export interface Transfer {
    "id": number;
    "kind": TransferKind;
    "title": string;
    "dest": string;
    "current": string;
    "totalBytes": number;
    "doneBytes": number;
    "files": number;
    "doneFiles": number;
    "state": TransferState;
    "error": string;
    "started": string;
    "rateBps": number;
}

export enum TransferKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindUpload = "upload",
    KindDownload = "download",
    KindOpen = "open",
    KindCopy = "copy",
};

export enum TransferState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateQueued = "queued",
    StateRunning = "running",
    StateDone = "done",
    StateFailed = "failed",
    StateCancelled = "cancelled",
};

/**
 * UpdateStatus is what the UI shows about updates.
 */
export interface UpdateStatus {
    "currentVersion": string;

    /**
     * State is one of: disabled, idle, checking, up-to-date, downloading,
     * ready, manual, error.
     */
    "state": string;

    /**
     * LatestVersion is set when a newer release was found.
     */
    "latestVersion": string;
    "notes": string;
    "releaseUrl": string;
    "error": string;
    "checkedAt": string;

    /**
     * PackageManaged is set when Nova was installed by a package manager
     * (pacman, apt, dnf) and should be updated with it.
     */
    "packageManaged": boolean;

    /**
     * ApkPath is the downloaded update on Android, handed to the installer.
     */
    "apkPath": string;
}

/**
 * UsageSeries is one chart's worth of data for the UI.
 */
export interface UsageSeries {
    "kind": string;
    "timestamps": string[] | null;
    "amounts": number[] | null;
    "total": number;
}
