// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nova$0 from "../internal/nova/models.js";

/**
 * Entry is a filesystem node as the UI sees it.
 */
export interface Entry {
    "id": string;
    "name": string;
    "path": string;
    "isDir": boolean;
    "size": number;
    "mime": string;
    "modified": string;
    "created": string;
    "mode": string;
    "owner": string;
    "sha256": string;
    "shared": boolean;

    /**
     * Trash only: where the item came from.
     */
    "origPath"?: string;
    "deletedAt"?: string | null;
}

export interface Folder {
    "path": string;
    "crumbs": Entry[] | null;
    "children": Entry[] | null;
    "canWrite": boolean;
}

/**
 * FolderSize sums file sizes below p. Directories only report their own size.
 */
export interface FolderSize {
    "bytes": number;
    "files": number;
    "folders": number;
}

/**
 * OpResult reports partial failure of a batch operation.
 */
export interface OpResult {
    "done": string[] | null;
    "errors": string[] | null;

    /**
     * From holds the source path of each Done entry, for operations that move.
     */
    "from"?: string[] | null;
}

/**
 * Session is the signed-in state shown to the UI.
 */
export interface Session {
    "signedIn": boolean;
    "server": string;
    "user": nova$0.User | null;
}

/**
 * Transfer is one batch job (upload of several files, download of a folder...).
 */
export interface Transfer {
    "id": number;
    "kind": TransferKind;
    "title": string;
    "dest": string;
    "current": string;
    "totalBytes": number;
    "doneBytes": number;
    "files": number;
    "doneFiles": number;
    "state": TransferState;
    "error": string;
    "started": string;
    "rateBps": number;
}

export enum TransferKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindUpload = "upload",
    KindDownload = "download",
    KindOpen = "open",
    KindCopy = "copy",
};

export enum TransferState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateQueued = "queued",
    StateRunning = "running",
    StateDone = "done",
    StateFailed = "failed",
    StateCancelled = "cancelled",
};
