// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ThemeService follows the desktop's colour scheme, accent colour, font and
 * colour theme.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Current returns the desktop's look as last read.
 */
export function Current(): $CancellablePromise<$models.SystemTheme> {
    return $Call.ByID(975691061);
}

/**
 * WindowColour is what a new window shows before its page has painted:
 * the page background Nova will use, so opening a window doesn't flash.
 * pref is the style preference ("system", "light" or "dark").
 */
export function WindowColour(pref: string): $CancellablePromise<[number, number, number]> {
    return $Call.ByID(1913243168, pref);
}
