// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TransferService runs uploads and downloads in the background.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Cancel(id: number): $CancellablePromise<void> {
    return $Call.ByID(1472355416, id);
}

/**
 * CapturePhoto opens the phone's camera. The photo arrives in the page as
 * the "common:capture" event, which hands its path to UploadCapture.
 */
export function CapturePhoto(): $CancellablePromise<void> {
    return $Call.ByID(1625204876);
}

/**
 * ClearFinished forgets transfers that are no longer running.
 */
export function ClearFinished(): $CancellablePromise<void> {
    return $Call.ByID(1162054349);
}

/**
 * Copy copies remote paths into destDir. The API has no server-side copy, so
 * every file is streamed down and back up. Clashes get "name (copy)" names.
 */
export function Copy(paths: string[] | null, destDir: string): $CancellablePromise<$models.Transfer> {
    return $Call.ByID(1631501367, paths, destDir);
}

/**
 * Download copies remote paths (files or folders) into a local directory.
 */
export function Download(paths: string[] | null, localDir: string): $CancellablePromise<$models.Transfer> {
    return $Call.ByID(2190581466, paths, localDir);
}

/**
 * List returns all known transfers, oldest first.
 */
export function List(): $CancellablePromise<$models.Transfer[] | null> {
    return $Call.ByID(2228038310);
}

/**
 * Open downloads a file to the cache and opens it with the system default app.
 */
export function Open(p: string): $CancellablePromise<$models.Transfer> {
    return $Call.ByID(1437886802, p);
}

/**
 * PickAndDownload asks for a local folder and downloads paths into it.
 * Phones have no folder picker, so there files go to the Download folder.
 */
export function PickAndDownload(paths: string[] | null): $CancellablePromise<$models.Transfer | null> {
    return $Call.ByID(4066159220, paths);
}

/**
 * PickAndUpload asks for local files (or a folder) and uploads them into dir.
 */
export function PickAndUpload(dir: string, folders: boolean): $CancellablePromise<$models.Transfer | null> {
    return $Call.ByID(2786912205, dir, folders);
}

/**
 * Upload uploads local files and folders into the remote dir.
 */
export function Upload(dir: string, localPaths: string[] | null): $CancellablePromise<$models.Transfer> {
    return $Call.ByID(1214201023, dir, localPaths);
}

/**
 * UploadCapture uploads a photo or video the camera just took into dir,
 * named after when it was taken like camera apps do (IMG_20260925_143210.jpg),
 * and deletes the local copy once it is uploaded.
 */
export function UploadCapture(dir: string, localPath: string): $CancellablePromise<$models.Transfer> {
    return $Call.ByID(561081367, dir, localPath);
}
