// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService checks GitHub Releases in the background and prepares updates.
 * The platform-specific parts live in updates_desktop.go and updates_android.go.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckNow runs a check immediately and returns the resulting state.
 */
export function CheckNow(): $CancellablePromise<$models.UpdateStatus> {
    return $Call.ByID(3066504200);
}

/**
 * OpenReleasePage opens the release notes of the available version in the browser.
 */
export function OpenReleasePage(): $CancellablePromise<void> {
    return $Call.ByID(2441828574);
}

/**
 * Restart quits and relaunches into the downloaded version.
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(1507498371);
}

/**
 * Status returns the current update state.
 */
export function Status(): $CancellablePromise<$models.UpdateStatus> {
    return $Call.ByID(1557091882);
}
